### ISSUE TITLE
Unauthorized second time its used and forthwith

### ISSUE THREAD

**Issue by Maltazar** [MattMckenzy/Mail2Gotify#5]
Hi again

Im getting this all the time now:

 info: System.Net.Http.HttpClient.StaticTokenCaller<GotifyServiceAppProvider>.ClientHandler[101]
       Received HTTP response headers after 4.1181ms - 401
 info: System.Net.Http.HttpClient.StaticTokenCaller<GotifyServiceAppProvider>.LogicalHandler[101]
       End processing HTTP request after 4.2555ms - 401
 fail: Mail2Gotify.Services.CacheItemProcessingService[0]
       Could not communicate with Gotify: Mail2Gotify.Exceptions.UnauthorizedException: There was a downstream unauthorized communication error with status code Unauthorized: Unauthorized
          at Mail2Gotify.Services.IRestServiceCaller.HandleError(HttpRequestMessage httpRequestMessage, HttpResponseMessage response) in /app/Services/IRestServiceCaller.cs:line 187
          at Mail2Gotify.Services.IRestServiceCaller.SendAsync[T](String route, Dictionary`2 queryParameters, HttpMethod httpMethod, String postContent, String contentType, String credential) in /app/Services/IRestServiceCaller.cs:line 103
          at Mail2Gotify.Services.IRestServiceCaller.PostRequestAsync[T](String route, Dictionary`2 queryParameters, String content, String contentType, String credential)
          at Mail2Gotify.Services.GotifyService.PushMessage(GotifyMessage gotifyMessage, String credential) in /app/Services/GotifyService.cs:line 18
          at Mail2Gotify.Services.CacheItemProcessingService.ProcessCacheItems() in /app/Services/CacheItemProcessingService.cs:line 32

Somehow, it worked the first time, or may also the second time - but now its stuck in unauthorized ? If I use Curl it just works with the same token - so something is a bit strange.
the mail is send to the Mail2Gotify server, and the forward of the mail user and password from the Mail2Gotify to gotify is giving the problem - or i'm doing something very wrong :D

could there be something with the cache? or something else?

**Comment by Maltazar** [comment]
my cache item looks like this, credential where the correct token - maybe the missing AppID is the problem?


{
    "Key": "638446389341939873",
    "CacheTime": "2024-02-27T13:55:34.1939873+00:00",
    "Credential": "*************",
    "GotifyMessage": {
        "AppId": null,
        "Date": "2024-02-27T13:55:34.1939873+00:00",
        "Id": null,
        "Message": "",
        "Priority": 5,
        "Title": "sore sends (unit@alarm.lan)"
    }
}

**Comment by Maltazar** [comment]
hmm curl is working against it - so it must be related to the way i send the mail though postfix
